POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "someuser",
    "name": "noname",
    "password": "password"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "whatever",
    "password": "code"
}